apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis                # Name of the HelmRelease resource
  namespace: default        # Namespace where Redis will be installed
spec:
  releaseName: redis        # Name of the Helm release
  chart:
    spec:
      chart: redis          # Name of the Helm chart to be deployed
      version: "14.8.2"     # Version of the Helm chart to be deployed
      sourceRef:
        kind: HelmRepository     # Specifies the kind of the source (HelmRepository in this case)
        name: redis              # Name of the HelmRepository resource
        namespace: flux-system   # Namespace where the HelmRepository is located
  interval: 5m              # Interval at which Flux should check for updates to the chart
  values:
    # Define your custom values for the Redis chart here
    # For example:
    # replicaCount: 3
    # resources:
    #   requests:
    #     memory: "64Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
